config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, only: [:edit, :update]
  resources :comentarios
  resources :procesos
  devise_for :users
  
  authenticated :user do
    root 'procesos#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'devise/sessions#new'
    end
  end

  get 'menu/diagrama_flujo'
  get 'menu/comentarios'
  get 'menu/cambios_aprobados', to: 'menu#cambios_aprobados' 
  get 'menu/estadisticas'
  get 'menu/contribuidores'
  get 'menu/procesos_pendientes', to: 'menu#procesos_pendientes'
  
  get 'cambio_estado_proceso/:valor/:id', to: 'menu#cambio_estado_proceso', as: 'cambio_estado_proceso'
  
  resources :posts do
  	resources :comments
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    
    def full_name
        self.nombre + " " + self.apellidos
    end
    
    
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to root_url, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:nombre, :apellidos, :fecha_nacimiento, :user_id, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :profile_nombre, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, id: :profile_apellidos, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>
  
  <div class="field">
    <%= form.label :fecha_nacimiento %>
    <%= form.datetime_select :fecha_nacimiento, id: :profile_fecha_nacimiento %>
  </div>

  <div class="actions">
    <%= form.submit "Actualizar perfil" , class: "btn btn-primary"%>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'procesos/nav' %>
<br>
<main role="main" class="container">
<div class="my-3 p-3 bg-white rounded box-shadow">
    <h1>Editar Perfil</h1>
    <br>
    <%= render 'form', profile: @profile %>
    
    <%= link_to 'Show', @profile %> |
    <%= link_to 'Back', profile_path %>
</div>
</main>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Fecha nacimiento</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.nombre %></td>
        <td><%= profile.apellidos %></td>
        <td><%= profile.fecha_nacimiento %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @profile.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @profile.apellidos %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @profile.fecha_nacimiento %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>