config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, only: [:edit, :update]
  resources :comentarios
  resources :procesos
  devise_for :users
  
  authenticated :user do
    root 'procesos#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'devise/sessions#new'
    end
  end

  get 'menu/diagrama_flujo'
  get 'menu/comentarios'
  get 'menu/cambios_aprobados', to: 'menu#cambios_aprobados' 
  get 'menu/estadisticas'
  get 'menu/contribuidores'
  get 'menu/procesos_pendientes', to: 'menu#procesos_pendientes'
  
  get 'cambio_estado_proceso/:valor/:id', to: 'menu#cambio_estado_proceso', as: 'cambio_estado_proceso'
  
  resources :posts do
  	resources :comments
  end

end

app/models/comentario.rb
class Comentario < ApplicationRecord
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:idUsuario, :descripcion, :fecha)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idUsuario %>
    <%= form.text_field :idUsuario, id: :comentario_idUsuario %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :comentario_descripcion %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.text_field :fecha, id: :comentario_fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<%= render 'procesos/nav' %>


<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th style="display:none" >Idusuario</th>
      <th>Descripcion</th>
      <th >Fecha</th>
      <th colspan="3" style="display:none"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr >
        <td style="display:none"><%= comentario.idUsuario %></td>
        <td class="col-md-10">
            <div class="card border-dark mb-3">
          <div class="card-body text-dark" style="background: #e3faf4;">
      <!--p class="card-text">Luis committed on 28 an 2018</p>-->
      <h5 class="card-title">    <%= comentario.descripcion %> </h5></td>
        <td><%= comentario.fecha %></td>
        <td style="display:none"><%= link_to 'Show', comentario %></td>
        <td style="display:none"><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td style="display:none"><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idusuario:</strong>
  <%= @comentario.idUsuario %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @comentario.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @comentario.fecha %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>