config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, only: [:edit, :update]
  resources :comentarios
  resources :procesos
  devise_for :users
  
  authenticated :user do
    root 'procesos#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'devise/sessions#new'
    end
  end

  get 'menu/diagrama_flujo'
  get 'menu/comentarios'
  get 'menu/cambios_aprobados', to: 'menu#cambios_aprobados' 
  get 'menu/estadisticas'
  get 'menu/contribuidores'
  get 'menu/procesos_pendientes', to: 'menu#procesos_pendientes'
  
  get 'cambio_estado_proceso/:valor/:id', to: 'menu#cambio_estado_proceso', as: 'cambio_estado_proceso'
  
  resources :posts do
  	resources :comments
  end

end

app/models/proceso.rb
class Proceso < ApplicationRecord
    belongs_to :user
    has_many :record
end

app/controllers/procesos_controller.rb
class ProcesosController < ApplicationController
  before_action :set_proceso, only: [:show, :edit, :update, :destroy]

  # GET /procesos
  # GET /procesos.json
  def index
    @procesos = Proceso.all
  end

  # GET /procesos/1
  # GET /procesos/1.json
  def show
  end

  # GET /procesos/new
  def new
    @proceso = current_user.procesos.build
  end

  # GET /procesos/1/edit
  def edit
  end

  # POST /procesos
  # POST /procesos.json
  def create
    @proceso = current_user.procesos.build(proceso_params)

    respond_to do |format|
      if @proceso.save
        format.html { redirect_to @proceso, notice: 'Proceso was successfully created.' }
        format.json { render :show, status: :created, location: @proceso }
      if @proceso.status == "Solicitud de Aprobacion"
        record = Record.new
        record.proceso_id = @proceso.id
        record.user_edit = current_user.email
        record.version_edit = Proceso.where(user_id: current_user.id).last.version
        record.save
      end
      else
        format.html { render :new }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procesos/1
  # PATCH/PUT /procesos/1.json
  def update
    respond_to do |format|
      if @proceso.update(proceso_params)
        format.html { redirect_to @proceso, notice: 'Proceso was successfully updated.' }
        format.json { render :show, status: :ok, location: @proceso }
      if @proceso.status == "Solicitud de Aprobacion"
        record = Record.new
        record.proceso_id = @proceso.id
        record.user_edit = current_user.email
        record.version_edit = Proceso.where(user_id: current_user.id).last.version
        record.save
      end
      else
        format.html { render :edit }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procesos/1
  # DELETE /procesos/1.json
  def destroy
    @proceso.destroy
    respond_to do |format|
      format.html { redirect_to procesos_url, notice: 'Proceso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proceso
      @proceso = Proceso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proceso_params
      params.require(:proceso).permit(:nombre, :commits, :status, :contribuidores, :version)
    end
end

app/helpers/procesos_helper.rb
module ProcesosHelper
end

app/views/procesos/_flujo.html.erb
<script>
  window.onload = function () {
      var btn = document.getElementById("run"),
          cd = document.getElementById("code"),
          chart;

      (btn.onclick = function () {
          var code = cd.value;

          if (chart) {
            chart.clean();
          }

          chart = flowchart.parse(code);
          chart.drawSVG('canvas', {
            // 'x': 30,
            // 'y': 50,
            'line-width': 3,
            'maxWidth': 3,//ensures the flowcharts fits within a certian width
            'line-length': 50,
            'text-margin': 10,
            'font-size': 14,
            'font': 'normal',
            'font-family': 'Helvetica',
            'font-weight': 'normal',
            'font-color': 'black',
            'line-color': 'black',
            'element-color': 'black',
            'fill': 'white',
            'yes-text': 'yes',
            'no-text': 'no',
            'arrow-end': 'block',
            'scale': 1,
            'symbols': {
              'start': {
                'font-color': 'red',
                'element-color': 'green',
                'fill': 'yellow'
              },
              'end':{
                'class': 'end-element'
              }
            },
            'flowstate' : {
              'past' : { 'fill' : '#CCCCCC', 'font-size' : 12},
              'current' : {'fill' : 'yellow', 'font-color' : 'red', 'font-weight' : 'bold'},
              'future' : { 'fill' : '#FFFF99'},
              'request' : { 'fill' : 'blue'},
              'invalid': {'fill' : '#444444'},
              'approved' : { 'fill' : '#58C4A3', 'font-size' : 12, 'yes-text' : 'APPROVED', 'no-text' : 'n/a' },
              'rejected' : { 'fill' : '#C45879', 'font-size' : 12, 'yes-text' : 'n/a', 'no-text' : 'REJECTED' }
            }
          });

          $('[id^=sub1]').click(function(){
            alert('info here');
          });
      })();

  };
</script>
<div>
  <textarea id="code" style="width: 100%;" rows="11">
    st=>start: Inicio
    e=>end: Fin
    op1=>operation: actividad1
    op2=>operation: actividad2
    sub1=>subroutine: Subproceso
    cond1=>condition: condicion1
    cond2=>condition: condicion2
    io=>inputoutput: comentario
    op3=>operation: actividad3
    op4=>operation: actividad4

    st->op1(right)->cond1
    cond1(yes, right)->cond2
    cond1(no)->sub1(left)->op1
    cond2(yes)->io->op3->op4->e
    cond2(no)->op2->e
  </textarea>
</div>
<div><button id="run" class="btn btn-success">Grafica flujo</button></div>
        <div id="canvas"></div>

app/views/procesos/_flujo2.html.erb
<div class="notes" data-locale="" data-lbl-localimg="">
    <div class="container">
        <div class="btn-group btn-group-sm">
            <a class="btn btn-light" title="New&emsp;&emsp;&emsp;Ctlr+T" data-nts-cmd="new">
                <i class="far fa-file"></i>
            </a>
            <a class="btn btn-light" title="Open&emsp;&emsp;&emsp;Ctlr+O" data-nts-cmd="open">
                <i class="far fa-folder-open"></i>
            </a> 
            <a class="btn btn-light" title="Save&emsp;&emsp;&emsp;Ctlr+S" data-nts-cmd="save">
                <i class="far fa-save"></i>&nbsp;Guardar
            </a> 
            <a class="btn btn-light" title="Print&emsp;&emsp;&emsp;Ctlr+P" data-nts-cmd="print">
                <i class="fas fa-print"></i>
            </a>
            <a class="btn btn-light" title="Export" data-nts-cmd="export" data-param="png">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </div>
        <ul class="nav nav-tabs list-inline notes-tab hidden-print">
            <li><a href="#" title="New Tab&emsp;Ctlr+T"><i class="glyphicon glyphicon-plus"></i></a>
            </li>
        </ul>
        <div class="jh2d-editor">
            <div class="btn-group btn-group-sm">
                <button type="button" class="btn btn-light" data-jh-cmd="shape" data-type="line" title="Line" data-mode="4">
                    <i class="far fa-window-minimize"></i>
                </button>
                <button type="button" class="btn btn-light" data-jh-cmd="shape" data-type="line" data-header="2" title="Arrow" data-mode="4">
                    <i class="fas fa-long-arrow-alt-right"></i>
                </button>
                <button type="button" class="btn btn-light" data-jh-cmd="text" data-type="rect" title="Text Box">
                    <i class="fas fa-font"></i>
                </button>
                <button type="button" class="btn btn-light" data-jh-cmd="shape" data-type="rect" title="Rectangle">
                    <i class="fas fa-square"></i>
                </button>
                <button type="button" class="btn btn-light" data-jh-cmd="shape" data-type="oval" title="Oval">
                    <i class="fas fa-circle"></i>
                </button>
                <button type="button" class="btn btn-light dropdown-toggle" id="zoomBtn" data-toggle="dropdown" title="Zoom Level">
                    <span></span><span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#" data-jh-cmd="zoom" data-param="4">400%</a>
                    </li>
                    <li>
                        <a href="#" data-jh-cmd="zoom" data-param="2">200%</a>
                    </li>
                    <li>
                        <a href="#" data-jh-cmd="zoom" data-param="1">100%</a>
                    </li>
                    <li>
                        <a href="#" data-jh-cmd="zoom" data-param="0.66">66%</a>
                    </li>
                    <li>
                        <a href="#" data-jh-cmd="zoom" data-param="0.5">50%</a>
                    </li>
                    <li>
                        <a href="#" data-jh-cmd="zoom" data-param="0.33">33%</a>
                    </li>
                </ul>
                <button type="button" class="btn btn-light" title="Zoom In" data-jh-cmd="zoom" data-opt="1" data-param="0.1">
                    <i class="fas fa-search-plus"></i>
                </button>
                <button type="button" class="btn btn-light" title="Zoom Out" data-jh-cmd="zoom" data-opt="-1" data-param="0.1">
                    <i class="fas fa-search-minus"></i>
                </button>
            </div>
            <div class="jh2d-canvas">
                <div class="jh2d-text-box" contenteditable="true">
                </div>
                <div class="dropdown clearfix ctx-menu">
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu" style="display:block;position:static;margin-bottom:5px">
                        <li>
                            <a tabindex="-1" data-jh-cmd="edit" href="#">Edit Text</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a tabindex="-1" data-jh-cmd="group" data-param="group" href="#">Group</a>
                        </li>
                        <li>
                            <a tabindex="-1" data-jh-cmd="group" data-param="ungroup" href="#">Ungroup</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a data-jh-cmd="layer" data-param="bring2Forward" href="#">Bring Up</a>
                        </li>
                        <li>
                            <a data-jh-cmd="layer" data-param="send2Backward" href="#">Send Back</a>
                        </li>
                        <li>
                            <a data-jh-cmd="layer" data-param="bring2Front" href="#">On Top</a>
                        </li>
                        <li>
                            <a data-jh-cmd="layer" data-param="send2Back" href="#">On Bottom</a>
                        </li>
                        <li class="divider"></li>
                        <li class="dropdown disabled">
                            <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Align
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a data-jh-cmd="align" data-param="0" href="#">Left</a>
                                </li>
                                <li>
                                    <a data-jh-cmd="align" data-param="1" href="#">Right</a>
                                </li>
                                <li>
                                    <a data-jh-cmd="align" data-param="4" href="#">Top</a>
                                </li>
                                <li>
                                    <a data-jh-cmd="align" data-param="5" href="#">Bottom</a>
                                </li>
                                <li>
                                    <a data-jh-cmd="align" data-param="6" href="#">Vertical Center</a>
                                </li>
                                <li>
                                    <a data-jh-cmd="align" data-param="2" href="#">Horizontal Center</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <canvas>
            </div>        
        </div>
    </div>            
</div>

<div class="modal fade" id="myMsgBox" tabindex="-1" role="dialog" data-locales="Alert,Confirm,Prompt">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p class="text-danger"></p>
                <div class="form-group hidden">
                    <label for="__prompt" class="control-label"></label>
                    <input type="text" class="form-control" id="__prompt">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-which="1" data-dismiss="modal">Si</button>
                <button type="button" class="btn btn-danger" data-which="-1" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-default" data-which="0" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

app/views/procesos/_form.html.erb
<%= form_with(model: proceso, local: true) do |form| %>
  <% if proceso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proceso.errors.count, "error") %> prohibited this proceso from being saved:</h2>

      <ul>
      <% proceso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :proceso_nombre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :commits %>
    <%= form.text_field :commits, id: :proceso_commits, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select(:status, ['-Seleccionar-','Iniciado','En Elaboracion','Solicitud de Aprobacion'], {}, { :class => 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= form.label :contribuidores %>
    <%= form.text_field :contribuidores, id: :proceso_contribuidores, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :version %>
    <%= form.select(:version, ['-','v1.0','v1.1','v1.2','v1.3','v1.4','v1.5','v1.6','v1.7','v1.8','v1.9','v1.10'], {}, { :class => 'form-control' }) %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
  
<% end %>

<div> 
<%= render 'procesos/flujo'%>
<br> 
</div> 

app/views/procesos/_nav.html.erb
<div class="container">
<header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-md-4">
              <%= link_to procesos_path do %>
                <%= image_tag("logo.png", class: "mb-4",height: '50', width: '50') %>
              <% end %>  
          </div>
          <div class="col-md-4 text-center">
            <a class="blog-header-logo text-dark">FLUJOSHARE</a>
          </div>
          <div class="col-md-4 text-right">
            <a>
              <%= image_tag(current_user.avatar.url(:thumb), class: "rounded-circle",height: '40', width: '40') %>
            </a>
            &nbsp;&nbsp;
            <a class="nav-link dropdown-toggle badge badge-primary" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= current_user.friendly_name %> 
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </div>
</header>
</div>

<%= render 'layouts/contenedor_menu' %>

app/views/procesos/contribuidores.html.erb
Hola

app/views/procesos/edit.html.erb
<%= render 'procesos/nav' %>
<main role="main" class="container">
<div class="my-3 p-3 bg-white rounded box-shadow">
    <br> 
    <h1>Editing Proceso</h1>
    
    <%= render 'form', proceso: @proceso %>
    
    <%= link_to 'Show', @proceso %> |
    <%= link_to 'Back', procesos_path %>
</div>
</main>

app/views/procesos/index.html.erb
<%= render 'procesos/nav' %>

<main role="main" class="container">
<div class="my-3 p-3 bg-white rounded box-shadow">
<br>
  
  <div class="row">
    <div class="col-md-10 .col-sm-12">
      <h3><i class="fas fa-cog"></i> Procesos [<%=Proceso.count%>]</h3>
    </div>
    <div class="col-md-2 .col-sm-12">
      <%= link_to 'Nuevo Proceso', new_proceso_path, class: "btn btn-primary" %>
    </div>        
  </div>
  <br>
  <div class="table-responsive">
    <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Commits</th>
        <th>Status</th>
        <th>Contribuidores</th>
        <th>Versión</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @procesos.each do |proceso| %>
        <tr>
          <td><%= proceso.nombre %></td>
          <td><%= proceso.commits %></td>
          <td>
            <button type="button" class="btn <% if proceso.status == 'Solicitud de Aprobacion' %> btn-outline-warning <% elsif proceso.status == 'Rechazado' %> btn-outline-danger <% else %> btn-outline-success <% end %>"  aria-haspopup="true" aria-expanded="false" disabled>
              <%= proceso.status %>
            </button>
          </td>
          <td><%= proceso.contribuidores %></td>
          <td><%= proceso.version %></td>
          <td><%= link_to '', proceso, class: "btn btn-outline-primary fas fa-eye fa-2x" %></td>
          <td><%= link_to '', edit_proceso_path(proceso), class: "btn btn-outline-primary far fa-edit fa-2x" %></td>
          <td><%= link_to '', proceso, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary far fa-trash-alt fa-2x" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
</main>

app/views/procesos/new.html.erb
<%= render 'procesos/nav' %>
<br> 
<main role="main" class="container">
<div class="my-3 p-3 bg-white rounded box-shadow">
    <h3>Nuevo Proceso</h3>
    <%= render 'form', proceso: @proceso %>
    <%= link_to 'Back', procesos_path %>
</div> 
</main>

app/views/procesos/show.html.erb
<%= render 'procesos/nav' %>

<main role="main" class="container">
<div class="my-3 p-3 bg-white rounded box-shadow">
<br>
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Nombre:</strong>
    <%= @proceso.nombre %>
  </p>
  
  <p>
    <strong>Commits:</strong>
    <%= @proceso.commits %>
  </p>
  
  <p>
    <strong>Status:</strong>
    <%= @proceso.status %>
  </p>
  
  <p>
    <strong>Contribuidores:</strong>
    <%= @proceso.contribuidores %>
  </p>
  
  <p>
    <strong>Version:</strong>
    <%= @proceso.version %>
  </p>
  
  
  <%= link_to 'Edit', edit_proceso_path(@proceso) %> |
  <%= link_to 'Back', procesos_path %>
</div>
</main>