config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, only: [:edit, :update]
  resources :comentarios
  resources :procesos
  devise_for :users
  
  authenticated :user do
    root 'procesos#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'devise/sessions#new'
    end
  end

  get 'menu/diagrama_flujo'
  get 'menu/comentarios'
  get 'menu/cambios_aprobados', to: 'menu#cambios_aprobados' 
  get 'menu/estadisticas'
  get 'menu/contribuidores'
  get 'menu/procesos_pendientes', to: 'menu#procesos_pendientes'
  
  get 'cambio_estado_proceso/:valor/:id', to: 'menu#cambio_estado_proceso', as: 'cambio_estado_proceso'
  
  resources :posts do
  	resources :comments
  end

end

app/views/layouts/_contenedor_menu.html.erb
<div class="container">
<nav class="navbar" style="background-color: #FFF;">
    
    <li class="nav-item">
        <a><%= link_to "Diagramas de flujo", procesos_path, class: "p-2 text-muted" %></a>    
    </li>
    <% if current_user.role == "admin" %>
        <li class="nav-item">
            <a><%= link_to "Procesos Pendientes", menu_procesos_pendientes_path, class: "p-2 text-muted" %>
                <% if Proceso.where(status: "Solicitud de Aprobacion").count != 0 %>
                    <span class="badge badge-danger"><%= Proceso.where(status: "Solicitud de Aprobacion").count %></span>
                <% end %>
            </a>    
        </li>
    <% end %>
    <li class="nav-item">
        <a><%= link_to "Comentarios", posts_path, class: "p-2 text-muted" %></a>
    </li>
    <li class="nav-item">
        <a><%= link_to "Cambios aprobados", menu_cambios_aprobados_path, class: "p-2 text-muted" %></a>    
    </li>
    <li class="nav-item">
        <a><%= link_to "Estadísticas", menu_estadisticas_path, class: "p-2 text-muted" %></a>   
    </li>
    <li class="nav-item">
        <a><%= link_to "Contribuidores", menu_contribuidores_path, class: "p-2 text-muted" %></a>    
    </li>
</nav>
</div>

<div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Posts', '#' %></li>
        <% if current_user %>
        <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

        <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

        <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flujoshare</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= favicon_link_tag 'favicon.ico' %>
    
  </head>
    
  <body>
  <div class="container">
    <div class="row">
    <%if notice %>
      <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <%elsif alert %>
      <div id=" notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <%end%>  
    </div>
  </div>
    
  <%= yield %>  
    
  <script>
    $(document).ready(function(){
      setTimeout(function(){
        $('#notice_wrapper').fadeOut("slow", function(){
          $(this).remove();
        })
      }, 1500);
    });
  </script>  

  </body>

</html>